export const projectData = [
	{
		id: "1",
		name: "instaCam",
		heading: "A social media app.",
		about: `It is made using React library and routing is done using React router. This app talks to a backend express app to fetch all the dynamic data from MongoDB atlas using the mongoose library. Login is made possible using JWT.
		
		Functionalities- create posts, edit user profile, follow/unfollow users, like/dislike posts, authentication, notifications.`,
		techStack: ["React", "Redux", "Express", "MongoDB", "Mongoose", "JWT"],
		image: "/assets/instaCam.png",
		website: "https://instacam.utsavkumar.tech",
		github: "https://github.com/utsavkumar-280/instacam",
		route: "instacam",
	},
	{
		id: "2",
		name: "VizzTube",
		heading: "A video library app for photography and filmmaking,",
		about:
			"A video library app for photography and filmmaking, it has almost all the videos that a guy with a camera needs to learn. This app is made using React framework. It is a dynamic app and uses a backend express app to fetch data from a mongo database. This app's functions are data sorting/filtering, user login/signup and management, and playlist management.",
		techStack: [
			"React",
			"React Router",
			"Express",
			"MongoDB",
			"Mongoose",
			"JWT",
		],
		image: "/assets/vizztube.png",
		website: "https://vizztube.utsavkumar.tech",
		github: "https://github.com/utsavkumar-280/vizz-tube",
		route: "vizztube",
	},
	{
		id: "3",
		name: "Camkart",
		heading: "An e-commerce app.",
		about:
			"CamKart is an e-commerce app having almost every product that a guy with a camera needs. This app is made using React framework. It is a dynamic app and uses a backend express app to fetch data from a mongo database. Functionalities of this app are - data sorting/filtering; user login/signup and management; cart/wishlist management, address management, etc.",
		techStack: [
			"React",
			"React Router",
			"Express",
			"MongoDB",
			"Mongoose",
			"JWT",
		],
		image: "/assets/camkart.png",
		website: "https://camkart.utsavkumar.tech",
		github: "https://github.com/utsavkumar-280/cam-kart",
		route: "camkart",
	},
	{
		id: "4",
		name: "CineQuiz",
		heading: "A quiz app for people in love with cinema.",
		about:
			"It's a react app made using the Next.js framework with TypeScript. It has a catalog of quizzes that you can play and all your attempts are stored in the dashboard inside the localStorage. It talks to a backend express server that replies with the quiz data stored in MongoDB.",
		techStack: [
			"React",
			"Next.js",
			"TailwindCSS",
			"TypeScript",
			"Express",
			"MongoDB",
			"Mongoose",
		],
		image: "/assets/cinequiz.png",
		website: "https://cinequiz.vercel.app",
		github: "https://github.com/utsavkumar-280/cinequiz",
		route: "cinequiz",
	},
	{
		id: "5",
		name: "Fx UI",
		heading: "A CSS component library.",
		about:
			"Fx UI is a lightweight and utility-first CSS Library that can be composed to develop fast and powerful web interfaces, directly in your markup.",
		techStack: ["HTML", "CSS", "JavaScript"],
		image: "/assets/fxUI.png",
		website: "https://fx-ui.utsavkumar.tech",
		github: "https://github.com/utsavkumar-280/Fx-UI",
		route: "fxui",
	},
];
